python odm.py --head_less \
--backend cpu \
--skip_avatar_animation \
--multi_process \
--enable_gt_segmentation \
--output_dir output/odm \
--scene NY \
--outdoor_objects_max_num 2 \
--resolution 512 \
--num_agents 15 \
--config agents_num_15 \
--agent_type ella_seg \
--max_seconds 32400 \
--save_per_seconds 2 \
--lm_id gpt-4o
