python ViCo/env.py --head_less \
--backend gpu \
--multi_process \
--skip_avatar_animation \
--output_dir output/odm \
--scene DETROIT \
--enable_indoor_scene \
--enable_indoor_activities \
--enable_outdoor_objects \
--outdoor_objects_max_num 2 \
--resolution 512 \
--num_agents 15 \
--config agents_num_15 \
--agent_type ella \
--max_seconds 32400 \
--save_per_seconds 10 \
--lm_id gpt-4o
